### ISSUE TITLE
Console error when entering administrator account

### ISSUE THREAD

**Issue by AndyAlvarezDev** [afterlogic/aurora-corporate-8#1]
![image](https://user-images.githubusercontent.com/57560667/120870706-f35e0900-c56f-11eb-97fa-2b8a1b0b6439.png)
![image](https://user-images.githubusercontent.com/57560667/120870737-0d97e700-c570-11eb-8f44-dd5261c37cfc.png)

Apart from showing this error, the platform becomes slow in the administrative zone.

Aurora Corporate version 8.8.1

use the following settings to follow the script more closely
![image](https://user-images.githubusercontent.com/57560667/120871880-5e5d0f00-c573-11eb-8f93-bef41cd414db.png)

and the result was the following:
![image](https://user-images.githubusercontent.com/57560667/120871992-ae3bd600-c573-11eb-90ff-e5d8041dc6b5.png)

![image](https://user-images.githubusercontent.com/57560667/120872036-d0355880-c573-11eb-9523-6cd65acc1d44.png)

**Comment by afterlogic-support** [comment]
Adminpanel runs a check whether main configuration file `data/settings/config.json` can be accessed over the web. If attempting to load it results in an error, that actually means the installation is secure.

**Comment by AndyAlvarezDev** [comment]
this error is generated to all users in general, not only in the administration panel. Is that normal too?

**Comment by AndyAlvarezDev** [comment]
this error is generated to all users in general, not only in the administration panel. Is that normal too?

**Comment by afterlogic-support** [comment]
This error can only be displayed for admin user. Apart from superadmin, it can be displayed if you have multi-tenancy enabled (by setting "EnableMultiTenant" to **true** in `data/settings/config.json` file) and current user was set as a tenant administrator (and that's something only superadmin can do). 

If you actually get that error for a normal user, we'll need steps on reproducing the error, as we were unable to reproduce it on a blank installation of Aurora Corporate.
