### ISSUE TITLE
Mobile Version No Signup form avaiable?

### ISSUE THREAD

**Issue by NRSHAOWN** [afterlogic/aurora-corporate-8#7]
there is no sign up form showing in signup url at mobile version, why?

**Comment by afterlogic-support** [comment]
Currently, signup feature is only available for desktop version of the interface.

**Comment by NRSHAOWN** [comment]
Can I Customize The Page for Mobile Version?  Which Module should customize?

**Comment by afterlogic-support** [comment]
This resource is for reporting issues. If you requires assistance with the source code customization, this can be arranged in terms of paid Professional Services contract. Please contact us [via Helpdesk](https://s.afterlogic.com/helpdesk/) if interested.
